<?php

use Phinx\Migration\AbstractMigration;

class CreateBase extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     *
     * Uncomment this method if you would like to use it.
     *
    public function change()
    {
    }
    */

    /**
     * Migrate Up.
     */
    public function up()
    {
        $queries = array(
            "DROP TABLE IF EXISTS `accounts`",
            "CREATE TABLE `accounts` ( `id` int(11) NOT NULL AUTO_INCREMENT, `account_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `permalink` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `logo_file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `logo_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `logo_file_size` int(11) DEFAULT NULL, `logo_updated_at` datetime DEFAULT NULL, `accepted` tinyint(1) DEFAULT '0', `first_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `last_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `postal_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `is_503c` tinyint(1) DEFAULT '0', `accepted_terms` tinyint(1) DEFAULT '0', `beta_features` tinyint(1) DEFAULT '0', `reply_to_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `street_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `street_address_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `mailing_postal_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `mailing_country` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `time_zone` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `stripe_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `stripe_account_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `stripe_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `stripe_publishable_key` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `is_developer` tinyint(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `index_accounts_on_permalink` (`permalink`), KEY `stripe_account_id` (`stripe_account_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `api_keys`",
            "CREATE TABLE `api_keys` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `hash` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL, `created` int(11) DEFAULT NULL, `valid_until` int(11) DEFAULT NULL, `secret` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL, `account` int(11) DEFAULT NULL, `status` tinyint(1) DEFAULT '0', `auth_type` int(2) DEFAULT '1', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `api_logs`",
            "CREATE TABLE `api_logs` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created` int(11) DEFAULT NULL, `message` text, `type_string` varchar(255) DEFAULT NULL, `type` int(11) DEFAULT NULL, `account` int(11) DEFAULT NULL, `api_key` int(11) DEFAULT NULL, `trace` text, `uri` varchar(255) DEFAULT NULL, `ip` varchar(15) DEFAULT NULL, `user_agent` varchar(255) DEFAULT NULL, `version` int(2) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1",
            "DROP TABLE IF EXISTS `campaign_levels`",
            "CREATE TABLE `campaign_levels` ( `id` int(11) NOT NULL AUTO_INCREMENT, `amount` decimal(7,2) DEFAULT NULL, `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `position` int(11) DEFAULT NULL, `campaign_id` int(11) NOT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `status` tinyint(1) NOT NULL DEFAULT '1', PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `campaigns`",
            "CREATE TABLE `campaigns` ( `id` int(11) NOT NULL AUTO_INCREMENT, `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `description` text COLLATE utf8_unicode_ci NOT NULL, `target` bigint(20) DEFAULT '0', `current` bigint(20) DEFAULT '0', `account_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `status` tinyint(1) DEFAULT '1', `fb_shares` int(11) DEFAULT '0', `campaign_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `twitter_shares` int(11) DEFAULT '0', `hash_tag` varchar(255) COLLATE utf8_unicode_ci DEFAULT '', `campaign_image_file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_image_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_image_file_size` int(11) DEFAULT NULL, `campaign_image_updated_at` datetime DEFAULT NULL, `youtube` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `enable_donation_levels` tinyint(4) DEFAULT '0', `campaign_id` int(11) DEFAULT NULL, `has_giving_opportunities` tinyint(1) DEFAULT '0', `street_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `street_address_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `postal_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `country` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `receipt_body` text COLLATE utf8_unicode_ci, `send_receipt` tinyint(1) DEFAULT '0', `use_campaign_address` tinyint(1) DEFAULT '1', `reply_to_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `bcc_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `email_org_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `minimum_donation_amount` int(11) DEFAULT '0', `analytics_id` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL, `total_donations` int(11) DEFAULT '0', `total_opportunities` int(11) DEFAULT '0', `display_donation_target` tinyint(1) NOT NULL DEFAULT '1', `display_donation_total` tinyint(1) NOT NULL DEFAULT '1', `header_font` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_color` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL, PRIMARY KEY (`id`), KEY `index_campaigns_on_campaign_token` (`campaign_token`), KEY `account_id` (`account_id`), KEY `campaign_id` (`campaign_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `ci_sessions`",
            "CREATE TABLE `ci_sessions` ( `session_id` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0', `ip_address` varchar(45) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0', `user_agent` varchar(120) COLLATE utf8_unicode_ci NOT NULL, `last_activity` int(10) unsigned NOT NULL DEFAULT '0', `user_data` text COLLATE utf8_unicode_ci NOT NULL, PRIMARY KEY (`session_id`), KEY `last_activity_idx` (`last_activity`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_campaign_field_responses`",
            "CREATE TABLE `custom_campaign_field_responses` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_response` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_field_id` int(11) DEFAULT NULL, `opportunity_id` int(11) DEFAULT NULL, `campaign_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_campaign_fields`",
            "CREATE TABLE `custom_campaign_fields` ( `id` int(11) NOT NULL AUTO_INCREMENT, `field_label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `field_required` tinyint(1) DEFAULT '0', `status` tinyint(1) DEFAULT '0', `campaign_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `position` int(11) DEFAULT NULL, `field_type` tinyint(1) DEFAULT '0', `field_options` text COLLATE utf8_unicode_ci, PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_form_responses`",
            "CREATE TABLE `custom_form_responses` ( `id` int(11) NOT NULL AUTO_INCREMENT, `user_response` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `field_id` int(11) DEFAULT NULL, `donation_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `field_label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_forms`",
            "CREATE TABLE `custom_forms` ( `id` int(11) NOT NULL AUTO_INCREMENT, `status` tinyint(1) DEFAULT '0', `campaign_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_options`",
            "CREATE TABLE `custom_options` ( `id` int(11) NOT NULL AUTO_INCREMENT, `status` tinyint(1) DEFAULT '0', `custom_select_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `position` int(11) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_selects`",
            "CREATE TABLE `custom_selects` ( `id` int(11) NOT NULL AUTO_INCREMENT, `label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `required` tinyint(1) DEFAULT '0', `status` tinyint(1) DEFAULT '0', `custom_form_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `position` int(11) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `custom_texts`",
            "CREATE TABLE `custom_texts` ( `id` int(11) NOT NULL AUTO_INCREMENT, `field_label` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `field_required` tinyint(1) DEFAULT '0', `status` tinyint(1) DEFAULT '0', `custom_form_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `position` int(11) DEFAULT NULL, `field_type` tinyint(1) DEFAULT '0', `field_options` text COLLATE utf8_unicode_ci, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `donations`",
            "CREATE TABLE `donations` ( `id` int(11) NOT NULL AUTO_INCREMENT, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `first_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `last_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `billing_address1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `billing_city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `billing_state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `billing_postal_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `billing_country` varchar(255) COLLATE utf8_unicode_ci DEFAULT '', `email_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `amount` bigint(20) DEFAULT '0', `express_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `express_payer_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_id` int(11) DEFAULT NULL, `contact` tinyint(1) DEFAULT '1', `referrer` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `account_id` int(11) DEFAULT NULL, `fb_share` tinyint(1) DEFAULT '0', `complete` tinyint(1) DEFAULT '0', `twitter_share` tinyint(1) DEFAULT '0', `offline` tinyint(1) NOT NULL DEFAULT '0', `original_amount` bigint(20) DEFAULT '0', `donation_date` datetime DEFAULT NULL, `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `campaign_group_id` int(11) DEFAULT NULL, `user_agent` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `donation_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `fb_send` int(11) DEFAULT '0', `stripe_charge_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `donation_level_id` int(11) DEFAULT NULL, `supporter_id` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `index_donations_on_account_id` (`account_id`), KEY `campaign_id` (`campaign_id`), KEY `campaign_group_id` (`campaign_group_id`), KEY `donation_token` (`donation_token`), KEY `stripe_charge_id` (`stripe_charge_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `hooks`",
            "CREATE TABLE `hooks` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `event` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `status` tinyint(3) unsigned DEFAULT NULL, `last_run` int(11) unsigned DEFAULT NULL, `account_id` int(11) unsigned DEFAULT NULL, `uuid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "DROP TABLE IF EXISTS `migrations`",
            "CREATE TABLE `migrations` ( `version` int(3) NOT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8",
            "DROP TABLE IF EXISTS `phinxlog`",
            "CREATE TABLE `phinxlog` ( `version` bigint(14) NOT NULL, `start_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, `end_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00') ENGINE=InnoDB DEFAULT CHARSET=utf8",
            "DROP TABLE IF EXISTS `schema_migrations`",
            "CREATE TABLE `schema_migrations` ( `version` varchar(255) COLLATE utf8_unicode_ci NOT NULL, UNIQUE KEY `unique_schema_migrations` (`version`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `share_logs`",
            "CREATE TABLE `share_logs` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `campaign_id` int(11) DEFAULT NULL, `opportunity_id` int(11) DEFAULT NULL, `donation_id` int(11) DEFAULT NULL, `share_type` enum('facebook','twitter') DEFAULT NULL, `referrer` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8",
            "DROP TABLE IF EXISTS `shares`",
            "CREATE TABLE `shares` ( `id` int(11) NOT NULL AUTO_INCREMENT, `campaign_id` int(11) DEFAULT NULL, `created_at` datetime DEFAULT NULL, `updated_at` datetime DEFAULT NULL, `referrer` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `share_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `fb_shares` int(11) DEFAULT '0', `tw_shares` int(11) DEFAULT '0', PRIMARY KEY (`id`), KEY `index_shares_on_campaign_id` (`campaign_id`), KEY `index_shares_on_fb_shares` (`fb_shares`), KEY `index_shares_on_tw_shares` (`tw_shares`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci",
            "DROP TABLE IF EXISTS `supporters`",
            "CREATE TABLE `supporters` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `account_id` int(11) NOT NULL, `email_address` varchar(255) NOT NULL, `first_name` varchar(255) NOT NULL, `last_name` varchar(255) NOT NULL, `postal_code` varchar(10) NOT NULL, `street_address` varchar(255) NOT NULL, `street_address_2` varchar(255) NOT NULL, `city` varchar(255) NOT NULL, `state` varchar(255) NOT NULL, `country` varchar(255) NOT NULL, `supporter_token` varchar(32) NOT NULL, `updated_at` datetime NOT NULL, `created_at` datetime NOT NULL, `donations_total` bigint(20) DEFAULT '0', `total_donations` int(11) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8",
            "DROP TABLE IF EXISTS `tasks`",
            "CREATE TABLE `tasks` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `event` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `hook_id` int(11) unsigned DEFAULT NULL, `next_run` int(11) unsigned DEFAULT NULL, `first_run` int(11) unsigned DEFAULT NULL, `created` int(11) unsigned DEFAULT NULL, `item` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `item_id` int(11) unsigned DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "DROP TABLE IF EXISTS `users`",
            "CREATE TABLE `users` ( `id` int(11) NOT NULL AUTO_INCREMENT, `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `crypted_password` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `password_salt` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `persistence_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `login_count` int(11) NOT NULL DEFAULT '0', `failed_login_count` int(11) NOT NULL DEFAULT '0', `last_request_at` datetime DEFAULT NULL, `current_login_at` datetime DEFAULT NULL, `last_login_at` datetime DEFAULT NULL, `current_login_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `last_login_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `account_id` int(11) NOT NULL, `perishable_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '', `single_access_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL, `active` tinyint(1) DEFAULT '1', `change_request` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `public_access_token` varchar(255) COLLATE utf8_unicode_ci NOT NULL, `is_super_admin` tinyint(1) DEFAULT '0', `signup_date` datetime DEFAULT NULL, PRIMARY KEY (`id`), KEY `index_users_on_email` (`email`), KEY `index_users_on_perishable_token` (`perishable_token`), KEY `index_users_on_single_access_token` (`single_access_token`), KEY `index_users_on_active` (`active`), KEY `account_id` (`account_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"
        );

        foreach ($queries as $q) {
            $this->adapter->execute($q);
        }
    }

    /**
     * Migrate Down.
     */
    public function down()
    {

    }
}